#
#   Replication script for:
#   
#   Ward, Michael D. and Andreas Beger, 2016, 
#
#
#

setwd("~/Work/jpr-forecasting-lessons")

library("packrat")

packrat::restore()
packrat::status()

# Create output directories for figures and tables
invisible(sapply(c("figures", "tables"), function(d) {
  if (!dir.exists(d)) dir.create(d)
  }))


# Estimate models, EBMA; forecast -----------------------------------------
#
#   If you want to skip the model/ensemble estimation, copy over
#   all the intermediate files generated by this script from the `tests/data`
#   folder. E.g.:
#     
#     cp tests/data/*.rda data/
#

source("R/estimate-and-forecast.R")


# Main figures/tables -----------------------------------------------------

#   Table II: EBMA and theme fit
#   _____________________________

source("R/table2.R")


#   Table III: Forecasts
#   ____________________

source("R/table3.R")


#   Figure 1a and b: ILC distributions
#   ____________________

source("R/ilc-summary.R")

#   Figure 3: EBMA and theme prediction violin plot and correlation matrix
#   Figure 5: EBMA weights vs model fit
#   Figure 6: EBMA and theme model barcode plots
#   ____________________

source("R/theme-summary.R")


#   Figure 7: Case-specific plots
#   ____________________

source("R/case-details.R")


# Appendix figures/tables -------------------------------------------------

#   Table A1: comparative model fit
#   Figure 1: ROC/PR plots
#   Figure 2: separation plots

source("R/ebma-alternatives.R")

#   Table A2: List of ILCs
#   Tables A3 to A9: theme model estimates
#   Table A10: comparison of regular, monthly test to 6-month test forecasts

source("R/appdx-tables.R")




